import Head from 'next/head'
import Script from 'next/script'
import styles from '../styles/Home.module.css'
import Slider from '../components/Slider'

export default function Home() {


  return (
    <div className={styles.container}>
      <Head>
        <title>Slider - Hepsiburada</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/color-thief/2.3.0/color-thief.umd.js"></Script>

      </Head>

      <main className={styles.main}>

        <Slider></Slider>
        
      </main>
    </div>
  )
}
